name: Node.js pipeline

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ExpressJs

    env:
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      MONGODB_SERVER: ${{secrets.MONGODB_SERVER}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependancies
        run: npm install

      - name: Run tests with Mocha
        run : npm test